#pragma once

void mcglViewport(int x, int y, int w, int h);
void mcglEnable(unsigned int cap);
void mcglDisable(unsigned int cap);
void mcglDepthFunc(unsigned int func);
void mcglClearColor(float r, float g, float b, float a);
void mcglMatrixMode(unsigned int mode);
void mcglLoadIdentity();
void mcglLoadMatrixf(const float *m);
void mcglBegin(unsigned int mode);
void mcglEnd();
void mcglColor4ub(unsigned char r, unsigned char g, unsigned char b, unsigned char a);
void mcglColor4f(float r, float g, float b, float a);
void mcglTexCoord2f(float u, float v);
void mcglVertex3f(float x, float y, float z);
void mcglTranslatef(float x, float y, float z);
void mcglRotatef(float angle, float x, float y, float z);
void mcglScalef(float x, float y, float z);
void mcglMultMatrixf(const float *m);
void mcglOrtho(double left, double right, double bottom, double top, double zNear, double zFar);
void mcglFrustum(double left, double right, double bottom, double top, double zNear, double zFar);
void mcglPushMatrix();
void mcglPopMatrix();
void mcglGetFloatv(unsigned int pname, float *params);
void mcglGenTextures(int n, unsigned int *textures);
void mcglDeleteTextures(int n, const unsigned int *textures);
void mcglBindTexture(unsigned int target, unsigned int texture);
void mcglTexImage2D(unsigned int target, int level, int internalformat, int width, int height, int border, unsigned int format, unsigned int type, const void *data);
void mcglTexSubImage2D(unsigned int target, int level, int xoffset, int yoffset, int width, int height, unsigned int format, unsigned int type, const void *data);
void mcglTexParameteri(unsigned int target, unsigned int pname, int value);
void mcglClear(unsigned int mask);
void mcglScissor(int x, int y, int w, int h);
void mcglDepthMask(unsigned char flag);
void mcglBlendFunc(unsigned int src, unsigned int dst);
void mcglBlendColor(float r, float g, float b, float a);
void mcglAlphaFunc(unsigned int func, float ref);
void mcglFrontFace(unsigned int mode);
void mcglLineWidth(float width);
void mcglColorMask(unsigned char r, unsigned char g, unsigned char b, unsigned char a);
void mcglPolygonOffset(float factor, float units);
void mcglFogi(unsigned int pname, int value);
void mcglFogf(unsigned int pname, float value);
void mcglFogfv(unsigned int pname, const float *params);
void mcglLightfv(unsigned int light, unsigned int pname, const float *params);
void mcglLightModelfv(unsigned int pname, const float *params);
void mcglShadeModel(unsigned int mode);
